[build]
  command = "npm run build"
  publish = "out"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"