export const mockQatarGeoData = {
  ip: "94.204.128.0",
  network: "94.204.128.0/24",
  version: "IPv4",
  city: "Doha",
  region: "Ad Dawhah",
  region_code: "DA",
  country: "QA",
  country_name: "Qatar",
  country_code: "QA",
  country_code_iso3: "QAT",
  country_capital: "Doha",
  country_tld: ".qa",
  continent_code: "AS",
  in_eu: false,
  postal: "",
  latitude: 25.3548,
  longitude: 51.1839,
  timezone: "Asia/Qatar",
  utc_offset: "+0300",
  country_calling_code: "+974",
  currency: "QAR",
  currency_name: "Rial",
  languages: "ar-QA,en",
  country_area: 11437,
  country_population: 2781677,
  asn: "AS51405",
  org: "Ooredoo Q.S.C"
};
